import type {Metadata} from 'next';
import './globals.css';
import './theme.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="theme1">
    <body>{children}</body>
    </html>
  );
}
