const fs = require('fs');

type Themes = Record<string,typeof theme1>;
const theme1 = {
  buttonBackground__Primary: '#009400',
  buttonBackgroundHover__Primary: '#00b200',
  buttonBackgroundActive__Primary: '#00d000',
  buttonBorder__Primary: '#b4b6b4',
  buttonText__Primary: '#fff',
  buttonBackground__Secondary: 'transparent',
  buttonBackgroundHover__Secondary: '#e6e6e6',
  buttonBackgroundActive__Secondary: '#d9d9d9',
  buttonBorder__Secondary: '#c3c4c3',
  buttonText__Secondary: '#777676',

  // Select -trigger
  selectBorderRadius__Primary: '4px',
  selectBorderColor__Primary: '#b4b6b4',
  selectBackgroundColor__Primary: '#fff',
  selectBoxShadow__Primary: '0 0 3px 0 #fff inset',
  selectBoxShadowHover__Primary: '0 2px 2px 0 #b4b6b4',
  selectText__Primary: '#000',
  selectPlaceholder__Primary: '#b4b6b4',
  // -disabled
  selectOpacityDisabled__Primary: '0.5',
  // -error
  selectBorderColorError__Primary: '#ff0000',
  selectBoxShadowError__Primary: '0 0 3px 0 #ff0000 inset',
  selectTextError__Primary: '#ff0000',
  // Select -menu
  selectMenuBackgroundColor__Primary: '#fff',
  selectMenuText__Primary: '#000',
  selectMenuItemDivider__Primary: '0 1px 0 0 #b4b6b4',
  selectMenuItemHover__Primary: '#e6e6e6',
  selectMenuItemSelected__Primary: '#e6e6e6',
  selectMenuItemSelectedMarker__Primary: '#ff0000',

  // Typography
  bodyFontFamily__Regular: 'Arial, Helvetica, sans-serif',
  bodyFontSize__Regular: '16px',
  bodyFontWeight__Regular: '400',
};

const theme2 = {
  buttonBackground__Primary: '#002a94',
  buttonBackgroundHover__Primary: '#0042b2',
  buttonBackgroundActive__Primary: '#0059d0',
  buttonBorder__Primary: '#b4b6b4',
  buttonText__Primary: '#fff',
  buttonBackground__Secondary: 'transparent',
  buttonBackgroundHover__Secondary: '#e6e6e6',
  buttonBackgroundActive__Secondary: '#d9d9d9',
  buttonBorder__Secondary: '#c3c4c3',
  buttonText__Secondary: '#777676',

  // Select -trigger
  selectBorderRadius__Primary: '4px',
  selectBorderColor__Primary: '#0f0fbb',
  selectBackgroundColor__Primary: '#fff',
  selectBoxShadow__Primary: '0 0 3px 0 #fff inset',
  selectBoxShadowHover__Primary: '0 2px 2px 0 #b4b6b4',
  selectText__Primary: '#000',
  selectPlaceholder__Primary: '#b4b6b4',
  // -disabled
  selectOpacityDisabled__Primary: '0.5',
  // -error
  selectBorderColorError__Primary: '#ff0000',
  selectBoxShadowError__Primary: '0 0 3px 0 #ff0000 inset',
  selectTextError__Primary: '#ff0000',
  // Select -menu
  selectMenuBackgroundColor__Primary: '#fff',
  selectMenuText__Primary: '#000',
  selectMenuItemDivider__Primary: '0 1px 0 0 #b4b6b4',
  selectMenuItemHover__Primary: '#e6e6e6',
  selectMenuItemSelected__Primary: '#e6e6e6',
  selectMenuItemSelectedMarker__Primary: '#ff0000',

  // Typography
  bodyFontFamily__Regular: 'Helvetica, Arial, sans-serif',
  bodyFontSize__Regular: '16px',
  bodyFontWeight__Regular: '600',
};

const themeGenerator = (themes: Themes) => {
  let css = '/* this file is auto generated by themeGenerator */ \n';
  for (const [name, theme] of Object.entries(themes)) {
    css += `.${name} { \n`;
    for (const key in theme) {
      // @ts-ignore
      css += `   --${key}: ${theme[key]};\n`;
    }
    css += '}\n\n';
  }

  fs.writeFileSync('./app/theme.scss', css);
  console.log('theme.css created');
};

themeGenerator({ theme1: theme1, theme2: theme2 });